rails_app/config/routes.rb
Rails.application.routes.draw do
  resources :estacionados
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'estacionados#index'
end

rails_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_app/app/models/cliente.rb
class Cliente < ApplicationRecord
end

rails_app/app/models/estacionado.rb
class Estacionado < ApplicationRecord
end

rails_app/app/models/user.rb
class User < ApplicationRecord
end

rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails_app/app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :endereco, :telefone)
    end
end

rails_app/app/controllers/estacionados_controller.rb
class EstacionadosController < ApplicationController
  before_action :set_estacionado, only: [:show, :edit, :update, :destroy]

  # GET /estacionados
  # GET /estacionados.json
  def index
    @estacionados = Estacionado.all
  end

  # GET /estacionados/1
  # GET /estacionados/1.json
  def show
  end

  # GET /estacionados/new
  def new
    @estacionado = Estacionado.new
  end

  # GET /estacionados/1/edit
  def edit
  end

  # POST /estacionados
  # POST /estacionados.json
  def create
    @estacionado = Estacionado.new(estacionado_params)

    respond_to do |format|
      if @estacionado.save
        format.html { redirect_to @estacionado, notice: 'Estacionado was successfully created.' }
        format.json { render :show, status: :created, location: @estacionado }
      else
        format.html { render :new }
        format.json { render json: @estacionado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estacionados/1
  # PATCH/PUT /estacionados/1.json
  def update
    respond_to do |format|
      if @estacionado.update(estacionado_params)
        format.html { redirect_to @estacionado, notice: 'Estacionado was successfully updated.' }
        format.json { render :show, status: :ok, location: @estacionado }
      else
        format.html { render :edit }
        format.json { render json: @estacionado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estacionados/1
  # DELETE /estacionados/1.json
  def destroy
    @estacionado.destroy
    respond_to do |format|
      format.html { redirect_to estacionados_url, notice: 'Estacionado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estacionado
      @estacionado = Estacionado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estacionado_params
      params.require(:estacionado).permit(:tipo_veiculo, :placa, :entrada, :saida, :valor)
    end
end

rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_app/app/helpers/clientes_helper.rb
module ClientesHelper
end

rails_app/app/helpers/estacionados_helper.rb
module EstacionadosHelper
end

rails_app/app/helpers/home_helper.rb
module HomeHelper
end

rails_app/app/helpers/users_helper.rb
module UsersHelper
end

rails_app/app/views/clientes/_form.html.erb
<%= form_for @cliente, :html => { :class => "form-horizontal cliente" } do |f| %>

  <% if @cliente.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @cliente.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :endereco, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :endereco, :class => 'form-control' %>
    </div>
    <%=f.error_span(:endereco) %>
  </div>
  <div class="form-group">
    <%= f.label :telefone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :telefone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:telefone) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                clientes_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

rails_app/app/views/clientes/edit.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

rails_app/app/views/clientes/index.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:endereco) %></th>
      <th><%= model_class.human_attribute_name(:telefone) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= link_to cliente.id, cliente_path(cliente) %></td>
        <td><%= cliente.nome %></td>
        <td><%= cliente.endereco %></td>
        <td><%= cliente.telefone %></td>
        <td><%=l cliente.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      cliente_path(cliente), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cliente_path(cliente), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cliente_path(cliente),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cliente_path,
            :class => 'btn btn-primary' %>

rails_app/app/views/clientes/new.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

rails_app/app/views/clientes/show.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @cliente.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:endereco) %>:</strong></dt>
  <dd><%= @cliente.endereco %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefone) %>:</strong></dt>
  <dd><%= @cliente.telefone %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              clientes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cliente_path(@cliente), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cliente_path(@cliente),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

rails_app/app/views/estacionados/_form.html.erb
<%= form_for @estacionado, :html => { :class => "form-horizontal estacionado" } do |f| %>

  <% if @estacionado.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@estacionado.errors.count, "error") %> prohibited this estacionado from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @estacionado.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :tipo_veiculo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :tipo_veiculo, :class => 'form-control' %>
    </div>
    <%=f.error_span(:tipo_veiculo) %>
  </div>
  <div class="form-group">
    <%= f.label :placa, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :placa, :class => 'form-control' %>
    </div>
    <%=f.error_span(:placa) %>
  </div>
  <div class="form-group">
    <%= f.label :entrada, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :entrada, :class => 'form-control' %>
    </div>
    <%=f.error_span(:entrada) %>
  </div>
  <div class="form-group">
    <%= f.label :saida, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :saida, :class => 'form-control' %>
    </div>
    <%=f.error_span(:saida) %>
  </div>
  <div class="form-group">
    <%= f.label :valor, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :valor, :class => 'form-control' %>
    </div>
    <%=f.error_span(:valor) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                estacionados_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

rails_app/app/views/estacionados/edit.html.erb
<%- model_class = Estacionado -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

rails_app/app/views/estacionados/index.html.erb
<%- model_class = Estacionado -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:tipo_veiculo) %></th>
      <th><%= model_class.human_attribute_name(:placa) %></th>
      <th><%= model_class.human_attribute_name(:entrada) %></th>
      <th><%= model_class.human_attribute_name(:saida) %></th>
      <th><%= model_class.human_attribute_name(:valor) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @estacionados.each do |estacionado| %>
      <tr>
        <td><%= link_to estacionado.id, estacionado_path(estacionado) %></td>
        <td><%= estacionado.tipo_veiculo %></td>
        <td><%= estacionado.placa %></td>
        <td><%= estacionado.entrada %></td>
        <td><%= estacionado.saida %></td>
        <td><%= estacionado.valor %></td>
        <td><%=l estacionado.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      estacionado_path(estacionado), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_estacionado_path(estacionado), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      estacionado_path(estacionado),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_estacionado_path,
            :class => 'btn btn-primary' %>

rails_app/app/views/estacionados/new.html.erb
<%- model_class = Estacionado -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

rails_app/app/views/estacionados/show.html.erb
<%- model_class = Estacionado -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:tipo_veiculo) %>:</strong></dt>
  <dd><%= @estacionado.tipo_veiculo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:placa) %>:</strong></dt>
  <dd><%= @estacionado.placa %></dd>
  <dt><strong><%= model_class.human_attribute_name(:entrada) %>:</strong></dt>
  <dd><%= @estacionado.entrada %></dd>
  <dt><strong><%= model_class.human_attribute_name(:saida) %>:</strong></dt>
  <dd><%= @estacionado.saida %></dd>
  <dt><strong><%= model_class.human_attribute_name(:valor) %>:</strong></dt>
  <dd><%= @estacionado.valor %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              estacionados_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_estacionado_path(@estacionado), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              estacionado_path(@estacionado),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>